### ISSUE TITLE
Print doesn't "finish" 

### ISSUE THREAD

**Issue by lin-ycv** [ThomasToka/MarlinFirmware#55] opened 2024-01-25 09:20 UTC
On v25, when a print is finished, the still shows the pause and stop buttons instead of finish, causing each print to be logged as a cancelled print.

**Comment by lin-ycv** [comment] 2024-01-25 10:00
Also it's possible to set 1 as y margin, which causes crashes.

**Comment by ThomasToka** [comment] 2024-01-25 11:11
The first i could reproduce. Will have a look later where the breaking change was.

But the second: You probably had a display glitch. Then the display beeps takes the value, shows it, but does not transmit it to the mainboard. Cause if it would transmit it to the mainboard the mainboard firmware bounced when entering a value lower 10 the min possible value of 10 back. The second part did not happen here. so you have seen the 1 on the display but the margin in the mainboard firmware wasnt changed. Here i can´t do nothing as in this moment nothing is transferred to the mainboard so i cant make any actions. Please reenter 1 -> it should be bounced to 10. If not do it again.

**Comment by lin-ycv** [comment] 2024-01-25 11:25
For setting the margin, I typed in 0, and it's would show up as 1, after that I ran a bed level, and it crashed.
I'm using the zero y offset mod.

**Comment by ThomasToka** [comment] 2024-01-25 11:41
Show me a pic of your:

probe offsets site 
home offsets site
leveling site with the margins

**Comment by ThomasToka** [comment] 2024-01-25 14:08
I have just uploaded the hotfixed binarys to address the finishing site bug.

The second i could not reproduce. So i need more data like requested earlier today.

**Closed as completed** 2024-01-26 10:12 UTC
Labels: bug, already hotfixed bug

**Comment by lin-ycv** [comment] 2024-01-26 11:05
Flashed back to v24 yesterday and did a printed, it just finished. I've now flashed back to v25 using the updated file, and the second issue of safety margin still exist.
![20240126_185323](https://github.com/ThomasToka/MarlinFirmware/assets/60565737/5e440f67-315e-493b-bd7f-fda660547885)
![20240126_185344](https://github.com/ThomasToka/MarlinFirmware/assets/60565737/62e714d1-10ab-400f-a2b8-c2f06d2281fa)
![20240126_185458](https://github.com/ThomasToka/MarlinFirmware/assets/60565737/ff8204e7-0f6f-4ccd-a046-657fe956f14f)
In this video you see how close it is to the edge, my home offset is off, so when levelling the rear points it probes outside the bed
https://github.com/ThomasToka/MarlinFirmware/assets/60565737/db0fceff-be4a-4f2a-b4c1-294837ae6a27

**Comment by ThomasToka** [comment] 2024-01-26 11:15
please show me additionally the about site of your printer.

**Comment by lin-ycv** [comment] 2024-01-26 11:53
![20240126_195005](https://github.com/ThomasToka/MarlinFirmware/assets/60565737/894d317e-6f1c-4f7a-982f-307aaf189c37)

**Comment by ThomasToka** [comment] 2024-01-26 12:09
cant reproduce this. :(
thats what i do:

- load firmware
- set home offsets to -2 and -2 over the touch
- set probe offsets to x to -46 and y 0 over the touch
- home printer
- set probes to 1 over the touch
- set x margin to 40, set y margin to 1 -> it reaccounts to 10 over the touch
- start autoleveling

how you do it exactly?

**Comment by lin-ycv** [comment] 2024-01-26 13:19
- Load firmware
- offset home -3,-3
- offset probe -46,0,-1.4
- go to bed level option
- set x margin to 0 (defaults to 40), set y to 0 (defaults to 1)
- start auto level

**Comment by ThomasToka** [comment] 2024-01-26 13:33
ok great now i could reproduce it.

set 1 to y and it will reaccount.

setting 0 does not reaccount in this constellation.

i will fix this also, but dont know if a hotfix or in the next version.

**Comment by ThomasToka** [comment] 2024-01-26 19:01
i have just pushed the hotfix for the 0 y issue:

https://github.com/ThomasToka/MarlinFirmware/releases/tag/MARLIN-E3S1PROFORK-BYTT-v025
